// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCityAlias(arg1, arg2) {
  return window['go']['app']['WailsApp']['AddCityAlias'](arg1, arg2);
}

export function ApplyReplyForJob(arg1, arg2, arg3) {
  return window['go']['app']['WailsApp']['ApplyReplyForJob'](arg1, arg2, arg3);
}

export function DeleteCity(arg1) {
  return window['go']['app']['WailsApp']['DeleteCity'](arg1);
}

export function DeleteDriver(arg1) {
  return window['go']['app']['WailsApp']['DeleteDriver'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['app']['WailsApp']['DeleteItem'](arg1);
}

export function GenerateReport(arg1, arg2, arg3) {
  return window['go']['app']['WailsApp']['GenerateReport'](arg1, arg2, arg3);
}

export function GetApprovalResults(arg1) {
  return window['go']['app']['WailsApp']['GetApprovalResults'](arg1);
}

export function GetCities() {
  return window['go']['app']['WailsApp']['GetCities']();
}

export function GetDrivers() {
  return window['go']['app']['WailsApp']['GetDrivers']();
}

export function GetItems() {
  return window['go']['app']['WailsApp']['GetItems']();
}

export function GetLastUnresolvedCities() {
  return window['go']['app']['WailsApp']['GetLastUnresolvedCities']();
}

export function GetOutboxJobs(arg1) {
  return window['go']['app']['WailsApp']['GetOutboxJobs'](arg1);
}

export function GetSettings() {
  return window['go']['app']['WailsApp']['GetSettings']();
}

export function ImportCitiesDict() {
  return window['go']['app']['WailsApp']['ImportCitiesDict']();
}

export function ImportDriversDict() {
  return window['go']['app']['WailsApp']['ImportDriversDict']();
}

export function ImportItemsDict() {
  return window['go']['app']['WailsApp']['ImportItemsDict']();
}

export function OpenFileLocation(arg1) {
  return window['go']['app']['WailsApp']['OpenFileLocation'](arg1);
}

export function PollRepliesNow() {
  return window['go']['app']['WailsApp']['PollRepliesNow']();
}

export function PollRepliesNowWithCount() {
  return window['go']['app']['WailsApp']['PollRepliesNowWithCount']();
}

export function ProcessWatchFolderNow() {
  return window['go']['app']['WailsApp']['ProcessWatchFolderNow']();
}

export function ResetSentRowsCounter() {
  return window['go']['app']['WailsApp']['ResetSentRowsCounter']();
}

export function SaveAutomationSettings(arg1) {
  return window['go']['app']['WailsApp']['SaveAutomationSettings'](arg1);
}

export function SaveCity(arg1) {
  return window['go']['app']['WailsApp']['SaveCity'](arg1);
}

export function SaveDriver(arg1) {
  return window['go']['app']['WailsApp']['SaveDriver'](arg1);
}

export function SaveItem(arg1) {
  return window['go']['app']['WailsApp']['SaveItem'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['app']['WailsApp']['SaveSettings'](arg1, arg2, arg3);
}

export function SelectOutputDir() {
  return window['go']['app']['WailsApp']['SelectOutputDir']();
}

export function SelectRawReport() {
  return window['go']['app']['WailsApp']['SelectRawReport']();
}

export function SelectTemplate() {
  return window['go']['app']['WailsApp']['SelectTemplate']();
}

export function SendReportNow(arg1) {
  return window['go']['app']['WailsApp']['SendReportNow'](arg1);
}
